info:
  description: who
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 2


---
spring:
  profiles: dev
info:
  description: abc